<?php

define('WAVECELL_SUB_ACCOUNT_ID', '');
define('WAVECELL_SECRET_KEY', '');
define('WAVECELL_SMS_FROM', '');
define('WAVECELL_COUNTRY', '');
define('WAVECELL_OTP_CODE_LENGTH', 6);
define('WAVECELL_OTP_CODE_VALIDITY', 600);
define('WAVECELL_RESEND_INTERVAL', 120);
define('WAVECELL_SMS_EXPIRED_IN_MINUTES', 60);
